# Generated by Django 3.2.6 on 2021-08-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raterprojectapi.category'),
            preserve_default=False,
        ),
    ]
