# Generated by Django 3.2.6 on 2021-08-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
    ]
