# Generated by Django 3.2.6 on 2021-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0003_remove_game_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='Category', through='raterprojectapi.GameCategory', to='raterprojectapi.Category'),
        ),
    ]
